### ISSUE TITLE
Files Application doesn't running

### ISSUE THREAD

**Issue by bong101** [cozy/cozy-sync#109]
Simply Files Applications seems not running...no button, no possible action

Best Regards

**Comment by poupotte** [comment]
Thanks @bong101 for your report,

Can you try to restart your files application ?
Can you try to refresh your page ?
Can you try to clean your cache (Ctrl F5) ?

**Comment by bong101** [comment]
Le 2016-01-28 08:53, poupotte a écrit : 

It woks now, thanks!! 

> Thanks @bong101 [1] for your report, 
> 
> Can you try to restart your files application ?
> Can you try to refresh your page ?
> Can you try to clean your cache (Ctrl F5) ? 
> 
> --
> Reply to this email directly or view it on GitHub [2].

  

Links:
------
[1] https://github.com/bong101
[2] https://github.com/cozy/cozy-sync/issues/109#issuecomment-176040969

**Comment by poupotte** [comment]
Nice :+1:
