### ISSUE TITLE
synchro impossible

### ISSUE THREAD

**Issue by stephanebrunet** [cozy/cozy-sync#110]
apres avoir saisie l'adresse et le mot de passe
j'ai un message d'erreur "Unexpected token <

sur un HTC one M7 
android 5.0.2
sense 6.0

**Comment by clochix** [comment]
Bonjour @stephanebrunet,

Pour pouvoir vous aider, j'aurais besoin d'un peu plus d'informations. Êtes-vous auto-hébergé, ou sur nos serveurs de test ?

**Comment by stephanebrunet** [comment]
Le 05/02/2016 17:46, Clochix a écrit :
>
> Bonjour @stephanebrunet <https://github.com/stephanebrunet>,
>
> Pour pouvoir vous aider, j'aurais besoin d'un peu plus d'informations. 
> Êtes-vous auto-hébergé, ou sur nos serveurs de test ?
>
sur votre serveur de test j'ai financer le projet serveur a la maison 
mais pas avant mars !
https://sbrunet.cozycloud.cc
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cozy/cozy-sync/issues/110#issuecomment-180434827>.
>


-- 
<Stephane Brunet>

Stephane Brunet <http://www.chapoulougne.com>
(33) 6 85 56 20 38

<CALLTO://sbconsult>

**Comment by stephanebrunet** [comment]
Le 05/02/2016 17:46,

Clochix

Bonjour
avez-vous trouvez la cause de ce "token inattendu"

merci
>
> Bonjour @stephanebrunet <https://github.com/stephanebrunet>,
>
> Pour pouvoir vous aider, j'aurais besoin d'un peu plus d'informations. 
> Êtes-vous auto-hébergé, ou sur nos serveurs de test ?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cozy/cozy-sync/issues/110#issuecomment-180434827>.
>


-- 
<Stephane Brunet>

Stephane Brunet <http://www.chapoulougne.com>
(33) 6 85 56 20 38

<CALLTO://sbconsult>

**Comment by clochix** [comment]
Bonjour @stephanebrunet,

désolé, j'avais oublié de vous répondre :-S

Non, désolé, je n'en sais pas plus.
Dans le champs adresse, vous tapez bien l'URL de votre serveur ?
Si vous refaite une tentative, merci de m'en indiquer précisément l'heure, afin que j'essaie de trouver des traces sur le serveur.

**Comment by stephanebrunet** [comment]
Le 09/02/2016 16:53,

Clochix

je viens de le faire ! meme message
sur un tel android (a jour)
avec cette adresse
https://sbrunet.cozycloud.cc/public/sync/principals/me/

> Bonjour @stephanebrunet <https://github.com/stephanebrunet>,
>
> désolé, j'avais oublié de vous répondre :-S
>
> Non, désolé, je n'en sais pas plus.
> Dans le champs adresse, vous tapez bien l'URL de votre serveur ?
> Si vous refaite une tentative, merci de m'en indiquer précisément 
> l'heure, afin que j'essaie de trouver des traces sur le serveur.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cozy/cozy-sync/issues/110#issuecomment-181924183>.
>


-- 
<Stephane Brunet>

Stephane Brunet <http://www.chapoulougne.com>
(33) 6 85 56 20 38

<CALLTO://sbconsult>

**Comment by clochix** [comment]
☺ J'ai compris !
L'adresse à taper est juste https://sbrunet.cozycloud.cc/
Celle que vous utilisez sert à synchroniser les calendriers via CalDAV, mais pas à configurer l'application mobile.
@poupotte peut-être faudrait-il gérer cela dans l'application mobile

**Comment by stephanebrunet** [comment]
Le 09/02/2016 17:13,

Clochix

je suis arrivé a l'etape 3
mais il me demande la mise a jour du proxy en 2.1 alors que sur le site 
je suis a 2.2
proxy :

[2016-02-09 16:21:35:995] error - app:error | Error: This name is already used
     at /usr/local/cozy/apps/proxy/build/server/controllers/devices.js:101:19
     at /usr/local/cozy/apps/proxy/build/server/controllers/devices.js:82:14
     at parseBody (/usr/local/cozy/apps/proxy/node_modules/request-json/main.js:35:12)
     at Request._callback (/usr/local/cozy/apps/proxy/node_modules/request-json/main.js:96:18)
     at Request.self.callback (/usr/local/cozy/apps/proxy/node_modules/request-json/node_modules/request/request.js:121:22)
     at Request.emit (events.js:98:17)
     at Request.<anonymous> (/usr/local/cozy/apps/proxy/node_modules/request-json/node_modules/request/request.js:978:14)
     at Request.emit (events.js:117:20)
     at IncomingMessage.<anonymous> (/usr/local/cozy/apps/proxy/node_modules/request-json/node_modules/request/request.js:929:12)
     at IncomingMessage.emit (events.js:117:20)


> ☺ J'ai compris !
> L'adresse à taper est juste https://sbrunet.cozycloud.cc/
> Celle que vous utilisez sert à synchroniser les calendriers via 
> CalDAV, mais pas à configurer l'application mobile.
> @poupotte <https://github.com/poupotte> peut-être faudrait-il gérer 
> cela dans l'application mobile
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cozy/cozy-sync/issues/110#issuecomment-181935502>.
>


-- 
<Stephane Brunet>

Stephane Brunet <http://www.chapoulougne.com>
(33) 6 85 56 20 38

<CALLTO://sbconsult>

**Comment by kosssi** [comment]
Coucou @stephanebrunet

L'erreur que tu vois ce produit lorsque ton device est déjà enregistré. Tu as deux possibilité : 
- changer le nom de ton device à l'installation de l'app mobile
- supprimer le device sur ton cozy dans l'application Status à droite

Dit moi si tu as encore un problème ;)

**Comment by stephanebrunet** [comment]
Le 09/02/2016 17:39,

  Simon

cela ne change rien c'est tjs une alerte pour me dire que le proxy est 
trop vieux
>
> Coucou @stephanebrunet <https://github.com/stephanebrunet>
>
> L'erreur que tu vois ce produit lorsque ton device est déjà 
> enregistré. Tu as deux possibilité :
>
>   * changer le nom de ton device à l'installation de l'app mobile
>   * supprimer le device sur ton cozy dans l'application Status à droite
>
> Dit moi si tu as encore un problème ;)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cozy/cozy-sync/issues/110#issuecomment-181948393>.
>


-- 
<Stephane Brunet>

Stephane Brunet <http://www.chapoulougne.com>
(33) 6 85 56 20 38

<CALLTO://sbconsult>

**Comment by poupotte** [comment]
Bonjour @stephanebrunet ,

Merci pour vos retours.

Effectivement, je rencontre également votre soucis. Nous devons publier une nouvelle version de l'application mobile d'ici la fin de la semaine.
Nous allons ajouter la correction de votre problème à cette publication.

Zoé

**Comment by poupotte** [comment]
Bonjour @stephanebrunet 

Je viens finalement de publier une nouvelle version (0.1.20) avec la correction de se problème :)
Elle devrait être disponible dans les heures à venir sur le playstore et  sur notre site.

Je  vous conseille de désinstaller l'ancienne version pour réinstaller la nouvelle.

Zoé

**Comment by clochix** [comment]
Bonsoir @stephanebrunet,

Une nouvelle version de l'application mobile vient d'être publiée, qui corrige ce problème. Pouvez-vous essayer de désinstaller l'ancienne, d'installer la nouvelle, et de vous connecter à nouveau à votre serveur ? Tout devrait, nous l'espérons, fonctionner à présent.

**Comment by stephanebrunet** [comment]
je teste ce soir merciiiiiii

Stephane

**Comment by stephanebrunet** [comment]
La synchro s'est bien passé

merci
>
> Bonjour @stephanebrunet <https://github.com/stephanebrunet>
>
> Je viens finalement de publier une nouvelle version (0.1.20) avec la 
> correction de se problème :)
> Elle devrait être disponible dans les heures à venir sur le playstore 
> et sur notre site.
>
> Je vous conseille de désinstaller l'ancienne version pour réinstaller 
> la nouvelle.
>
> Zoé
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cozy/cozy-sync/issues/110#issuecomment-182507013>.
>


-- 
<Stephane Brunet>

Stephane Brunet <http://www.chapoulougne.com>
(33) 6 85 56 20 38

<CALLTO://sbconsult>

**Comment by stephanebrunet** [comment]
Le 10/02/2016 21:05,

Clochix

Oui tout fonctionne merci
>
> Bonsoir @stephanebrunet <https://github.com/stephanebrunet>,
>
> Une nouvelle version de l'application mobile vient d'être publiée, qui 
> corrige ce problème. Pouvez-vous essayer de désinstaller l'ancienne, 
> d'installer la nouvelle, et de vous connecter à nouveau à votre 
> serveur ? Tout devrait, nous l'espérons, fonctionner à présent.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cozy/cozy-sync/issues/110#issuecomment-182555600>.
>


-- 
<Stephane Brunet>

Stephane Brunet <http://www.chapoulougne.com>
(33) 6 85 56 20 38

<CALLTO://sbconsult>

**Comment by clochix** [comment]
Génial, merci du signalement @stephanebrunet,
Et merci @poupotte et @kosssi pour la correction ☺

**Comment by stephanebrunet** [comment]
Le 12/02/2016 10:45,

Clochix

une autre question  apres avoir installé et configurer DAVdroid
Quand je poste un rdv sur https://sbrunet.cozycloud.cc/
il apparait apres synchro sur mon tel android;
en revanche tout ce qu'il a mon tel n'apparait pas sur 
https://sbrunet.cozycloud.cc/
le pensais que la synchro etait dans les deux sens ?

Cordialement

> Génial, merci du signalement @stephanebrunet 
> <https://github.com/stephanebrunet>,
> Et merci @poupotte <https://github.com/poupotte> et @kosssi 
> <https://github.com/kosssi> pour la correction ☺
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/cozy/cozy-sync/issues/110#issuecomment-183254587>.
>


-- 
<Stephane Brunet>

Stephane Brunet <http://www.chapoulougne.com>
(33) 6 85 56 20 38

<CALLTO://sbconsult>

**Comment by clochix** [comment]
Hello @stephanebrunet,

Je te confirme que la synchronisation doit fonctionner dans les deux sens. Est-ce que tu n'aurais pas plusieurs calendriers sur ton ordiphone ? Seuls les évènements créés dans le calendrier synchronisé avec ton Cozy apparaitront en ligne, ceux des calendriers locaux ne seront pas synchronisés.
