### ISSUE TITLE
Add Thunderbird Cardbook config informations

### ISSUE THREAD

**Issue by m4dz** [cozy/cozy-sync#125]
[Cardbook](https://addons.mozilla.org/fr/thunderbird/addon/cardbook/) is the new way to access carddav address book inside Thunderbird in a dedicated module.

It's way more stable than the Sogo Connector, so adding informations in the Sync app index to configure Cardbook can be a good choice.

**Comment by clochix** [comment]
I like this idea. Configuring Cardbook require the same informations as Sogo, so I just added its name. Unfortunately, this are translated strings, so I can't add a link to the addon page.

**Comment by frankrousseau** [comment]
If someone does that, it would be nice to inform that iOS information work on OSX too.

**Comment by clochix** [comment]
Done ;-)

**Comment by frankrousseau** [comment]
Thx

**Comment by poupotte** [comment]
Thanks @m4dz and @clochix
