### ISSUE TITLE
Sync issues with MacOS and iOS

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-sync#143]
A user is reporting by email a lot of sync issues with iOS and MacOS:
> Pour les contacts, je ne peux toujours pas synchroniser des photos de mon application Contacts vers le serveur. Il faut que je mette les photos en ligne directement sur mon Cozy dans Firefox pour que cela fonctionne. Et je ne sais par quel procédé, mon serveur s’est un peu cafouillé : ma liste de contacts s’est réactualisé avec une ancienne version sans tous mes contacts récents (je suis passé de 94 à 56 contacts puis à 41). Puis je suis repassé à 91 contacts. Du coup j'ai perdu quelques contacts.
> En terme de bug, je ne parviens par forcément à synchroniser les infos entre mes appareils iOS ou macOS et le serveur. C’est très aléatoire. Par exemple si j’ajoute un contact sur l’iPhone, il ne va pas se synchroniser vers le serveur. Si j’ajoute le contact sur le serveur via Firefox, il va se synchroniser sur l’iPhone.
> J’ai le même soucis avec le Calendrier : je peux synchroniser du serveur vers l’application sans soucis, mais si j’ajoute des infos dans l’application, elles ne sont pas copiées au serveur.

I don't see anything strange in logs on the server side.

**Comment by jsilvestre** [comment]
Hi, those are quite known issues that we haven't been able to fix so far: https://github.com/cozy/cozy-sync/issues/11 et https://github.com/cozy/cozy-sync/issues/136

I close here then.
