### ISSUE TITLE
Cal & Card @

### ISSUE THREAD

**Issue by AlroneRhyn** [cozy/cozy-sync#27]
Hi, 
CalDav : 
[Thunderbird] SERVEUR is missing  : 
https://SERVER/public/sync/calendars/me/my-calendar/
This address works with Apple OSX 10.9.4 too.

CardDav : 
SERVER is missing
https://SERVER/public/sync/principals/me/
Works with Apple OSX 10.9.4 too.

When you reset credentials, you have to log OFF log OUT, otherwise passwrd doesn't display.

Would be nice to change login.

![20140807_sync_cozy](https://cloud.githubusercontent.com/assets/8383459/3839916/ce18d010-1e16-11e4-8016-af7ace19f309.png)

**Comment by frankrousseau** [comment]
We made many fixes. @AlroneRhyn is it fixed?
