### ISSUE TITLE
Calendar Sync: Error 401 on some apps only

### ISSUE THREAD

**Issue by sylzys** [cozy/cozy-sync#70]
I changed my MacOS calendar software form iCal to BusyCal2 and tried others :

# iCal
Account adding and sync works fine on iCal:

```
PROPFIND /public/principals/me/ 207 7.507 ms - -                                
OPTIONS /public/principals/me/ 200 6.557 ms - -                                 
REPORT /public/principals 401 0.467 ms - -                                      
REPORT /public/principals 200 5.963 ms - -                                      
PROPFIND /public/calendars/me/ 401 0.454 ms - -                                 
PROPFIND /public/calendars/me/ 207 26.052 ms - -                                
PROPPATCH /public/calendars/me/ 207 6.316 ms - -                                
PROPPATCH /public/calendars/me/ 207 5.977 ms - -                                
PROPPATCH /public/calendars/me/mon%20agenda/ 207 9.317 ms - -                   
PROPPATCH /public/calendars/me/mon%20agenda/ 207 9.306 ms - -
```
Notice the strange 
````
PROPFIND /public/calendars/me/ 401 0.454 ms - - 
````
in the middle though.

# BusyCal2
When on BusyCal 2, I use the exact same settings (URL, protocol, credentials), but can't fetch anything :
```
PROPFIND /public/principals/me/ 401 8.503 ms - -                                
PROPFIND /public/principals/me/ 401 7.369 ms - -                                
PROPFIND /public/principals/me/ 401 8.026 ms - -  
...
```
Tried to change my password, iCal detected it and gave me a 401, which became a 207 after password change.
I also tried on both a Cozy test instance and on a personal instance.
On random, after several similars 401 errors, I managed to connect on my personal instance.

```
PROPFIND /public/principals/me/ 401 1.728 ms - -
PROPFIND /public/principals/me/ 207 15.876 ms - -
OPTIONS /public/principals/me/ 200 8.219 ms - -
REPORT /public/principals 401 0.669 ms - -
REPORT /public/principals 200 9.526 ms - -
PROPFIND /public/calendars/me/ 401 0.703 ms - -
PROPFIND /public/calendars/me/ 207 65.832 ms - -
PROPPATCH /public/calendars/me/ 207 20.734 ms - -
PROPPATCH /public/calendars/me/ 207 13.658 ms - -
PROPPATCH /public/calendars/me/mon%20agenda/ 207 17.343 ms - -
```
# Soho Organizer 9
Works fine

# aCal on Android
Works fine

**Comment by sylzys** [comment]
It seems that BusyCal2, contrary to iCal, doesn't need (doesn't support ?) the full URL like 
```
https://user.cozycloud.cc/public/sync/principals/me
```
Instead, it seems to react as DAVdroid does, i.e wanting the host only 
```
https://user.cozycloud.cc
```
That being said, it's strange that the error comes with an authentification failed (401)

**Comment by frankrousseau** [comment]
So the problem occurs only with BusyCal?

**Comment by m4dz** [comment]
The problem occurs with iOS native client too (see #69) as the PROPFIND method returns many times 401 instead of 207.

**Comment by sylzys** [comment]
I faced the problem with BusyCal, and not with other, during my tests.
Oddly, once, my online tests instance credentials were accepted, so now the cal is listed. And oddly again, I have no trouble syncing / adding / removing events.

On my local instance, I got no "bad credentials" error, but it keeps waiting and waiting, and the cal is never added. I'll paste the logs here.

**Comment by jsilvestre** [comment]
@sylzys do you still have the problem?

You mention a difference between your online and your local setup, which one are you actively using? Could this difference be the cause of the issue?

**Comment by sylzys** [comment]
oh my bad, I completely forgot this issue :/

I use Busycal on a daily basis for a long time now with Cozy, with no major problems :)
Thanks for your concern !
