### ISSUE TITLE
Cozy-Sync crash when I sync my contacts

### ISSUE THREAD

**Issue by obigroup** [cozy/cozy-sync#78]
Hello,

When I try to synchronize my contacts with my phone, cozy-sync crash with this message in log file: 
```
info: socket.io started
^[[90mGET / ^[[36m304 ^[[90m354.934 ms - -^[[0m
[Fri, 01 May 2015 18:44:37 GMT] - GET / - 304 - 355.937 ms -  -
^[[90mPUT /public/addressbooks/me/all-contacts/c87fb0b2973ec5f0746c2e32de280dd8.vcf ^[[33m412 ^[[90m127.721 ms - -^[[0m
^[[90mPROPFIND /public/addressbooks/me/all-contacts/ ^[[32m207 ^[[90m125.916 ms - -^[[0m

TypeError: Cannot call method 'toUpperCase' of undefined
    at Function.VCardParser.toVCF (/usr/local/cozy/apps/sync/node_modules/cozy-vcard/lib/index.js:576:28)
    at ModelConstructor.Contact.toVCF (/usr/local/cozy/apps/sync/build/server/models/contact.js:101:39)
    at /usr/local/cozy/apps/sync/build/server/backends/carddav.js:94:24
    at /usr/local/cozy/apps/sync/node_modules/async/lib/async.js:227:13
    at iterate (/usr/local/cozy/apps/sync/node_modules/async/lib/async.js:134:13)
    at /usr/local/cozy/apps/sync/node_modules/async/lib/async.js:145:25
    at /usr/local/cozy/apps/sync/node_modules/async/lib/async.js:229:17
    at /usr/local/cozy/apps/sync/build/server/backends/carddav.js:95:18
    at ModelConstructor.Contact.toVCF (/usr/local/cozy/apps/sync/build/server/models/contact.js:101:12)
    at /usr/local/cozy/apps/sync/build/server/backends/carddav.js:94:24
```

Especially when I remove a contact.

Thank you.

**Comment by aenario** [comment]
Hi @obigroup, The bug was in cozy-sync, it is caused because you have a "corrupted" contact in your cozy (ie. One of your contact as a datapoint with a value but no key `{"value":"xxxx"}` instead of `{"name": "tel", "value":"xxxx"}` ).

If you can find this contact and tell us where it came from, that would be helpful.

Anyway, the above-mentionned PR will make cozy-sync resilient to this case. Once it is merged in cozy-vcard, we will update cozy-sync dependencies.

**Comment by frankrousseau** [comment]
@aenario it's merged, dependencies can be updated.

**Comment by obigroup** [comment]
Hi @aenario ,

I looked on my contacts with databrowser app and I don't have a "corrupted" contact like: ```{"value":"xxxx"}```. Maybe it's come from my hebrews contacts ?
I have this bug just when I remove a contact (Not hebrew).

I imported my contacts in Vcard format from google contact export.

**Comment by obigroup** [comment]
@aenario 
Release date for a fix ?

**Comment by clochix** [comment]
Hi @obigroup,

Sorry for not updating this issue. The fix should have been released for quite a long time now. Do you think we can close the ticket?
