### ISSUE TITLE
Contact sync error

### ISSUE THREAD

**Issue by jsilvestre** [cozy/cozy-sync#84]
An user has trouble (the app crashes) while synching its contacts.

See https://forum.cozy.io/t/erreur-syncro-davdroid/648/5 for details.

**Comment by AntoineCa** [comment]
Same problem since 06/12.... The calendar is synchronized, but not contacts.
Logs : http://pastebin.com/winGR2ct

**Comment by jsilvestre** [comment]
It seems to be working again, so I close, feel free to reopen!
