### ISSUE TITLE
Calendar sync error

### ISSUE THREAD

**Issue by ZeHiro** [cozy/cozy-sync#87]
When my smartphone tries to sync the calendars on my cozy, I get this error : 

undefined
REPORT /public/calendars/me/Perso/ 501 729.838 ms - -

This is the only Calendar for which I get this error.

The client is Caldav-Sync (Android) 
I can provide the ical file on demand. 
If I launch "Synchronisation Longue" in the "Comptes et synchronisations" I can sync again the calandar

**Comment by clochix** [comment]
Hello @ZeHiro,
Thanks for reporting ! Would you mind sending us the ical file and the logs of Sync app ? Thanks !

**Comment by jsilvestre** [comment]
Hello @ZeHiro,

I tried to sync the calendar you provide with Caldav-Sync, and it's worked with either "Synchronisation Longue" enabled and disabled. Could you try to reinstall the Sync app?

**Comment by ZeHiro** [comment]
I tried, I got the same problem.
OPTIONS /public/calendars/me/Perso/ 401 11.769 ms - -
OPTIONS /public/calendars/me/Perso/ 200 149.370 ms - -
PROPFIND /public/calendars/me/Perso/ 207 177.608 ms - -
undefined
REPORT /public/calendars/me/Perso/ 501 987.594 ms - -
undefined
REPORT /public/calendars/me/Perso/ 501 911.300 ms - -
undefined
REPORT /public/calendars/me/Perso/ 501 746.011 ms - -

I also got this : 
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead

Could this come from the client?

**Comment by jsilvestre** [comment]
Can you please install https://github.com/jsilvestre/cozy-sync.git@development ? If should have more logs. Thanks!

**Comment by ZeHiro** [comment]
There's only one branch on your repo ;)

**Comment by jsilvestre** [comment]
Oups, sorry. Let's try with https://github.com/jsilvestre/cozy-sync.git then! Thank you.

**Comment by ZeHiro** [comment]
I installed it, and the log are not more verbose with this version.

**Comment by jsilvestre** [comment]
Oups, I did it again. Sorry, apparently my brain doesn't want to do things correctly :< 

I forgot something....can you please try again? Thank you for your patience, I am very sorry for my lack of precision/rigor.

**Comment by ZeHiro** [comment]
error - caldav:backend | ./build/server/backends/caldav.js:330 | CalendarQuery went wrong with the followingparameters:
error - caldav:backend | ./build/server/backends/caldav.js:331 | calendarId: Perso
error - caldav:backend | ./build/server/backends/caldav.js:332 | filters:
error - caldav:backend | ./build/server/backends/caldav.js:333 | {"name":"VCALENDAR","is-not-defined":false,"comp-filters":[{"name":"VEVENT","is-not-defined":false,"comp-filters":[],"prop-filters":[],"time-range":{"start":"2015-07-08T00:00:00.000Z","end":"2016-03-02T00:00:00.000Z"}}],"prop-filters":[],"time-range":null}
error - caldav:backend | ./build/server/backends/caldav.js:334 | 
error - caldav:backend | ./build/server/backends/caldav.js:330 | CalendarQuery went wrong with the followingparameters:
error - caldav:backend | ./build/server/backends/caldav.js:331 | calendarId: Perso
error - caldav:backend | ./build/server/backends/caldav.js:332 | filters:
error - caldav:backend | ./build/server/backends/caldav.js:333 | {"name":"VCALENDAR","is-not-defined":false,"comp-filters":[{"name":"VEVENT","is-not-defined":false,"comp-filters":[],"prop-filters":[],"time-range":{"start":"2015-07-08T00:00:00.000Z","end":"2016-03-02T00:00:00.000Z"}}],"prop-filters":[],"time-range":null}
error - caldav:backend | ./build/server/backends/caldav.js:334 | 
error - caldav:backend | ./build/server/backends/caldav.js:330 | CalendarQuery went wrong with the followingparameters:
error - caldav:backend | ./build/server/backends/caldav.js:331 | calendarId: Perso
error - caldav:backend | ./build/server/backends/caldav.js:332 | filters:
error - caldav:backend | ./build/server/backends/caldav.js:333 | {"name":"VCALENDAR","is-not-defined":false,"comp-filters":[{"name":"VEVENT","is-not-defined":false,"comp-filters":[],"prop-filters":[],"time-range":{"start":"2015-07-08T00:00:00.000Z","end":"2016-03-02T00:00:00.000Z"}}],"prop-filters":[],"time-range":null}
error - caldav:backend | ./build/server/backends/caldav.js:334 | 
error - caldav:backend | ./build/server/backends/caldav.js:330 | CalendarQuery went wrong with the followingparameters:
error - caldav:backend | ./build/server/backends/caldav.js:331 | calendarId: Perso
error - caldav:backend | ./build/server/backends/caldav.js:332 | filters:
error - caldav:backend | ./build/server/backends/caldav.js:333 | {"name":"VCALENDAR","is-not-defined":false,"comp-filters":[{"name":"VEVENT","is-not-defined":false,"comp-filters":[],"prop-filters":[],"time-range":{"start":"2015-07-08T00:00:00.000Z","end":"2016-03-02T00:00:00.000Z"}}],"prop-filters":[],"time-range":null}
error - caldav:backend | ./build/server/backends/caldav.js:334 | 
error - caldav:backend | ./build/server/backends/caldav.js:330 | CalendarQuery went wrong with the followingparameters:
error - caldav:backend | ./build/server/backends/caldav.js:331 | calendarId: Perso

**Comment by jsilvestre** [comment]
We haven't been able to isolate the issue yet. I pushed another version with more logs. Can you please update and try again? Be careful though, the newly added logs are going to leak some personal data (event's content) so you might want to send me the log by email.

Thank you again!

**Comment by ZeHiro** [comment]
I sent it on support chez cozy

**Comment by ZeHiro** [comment]
@jsilvestre 
Did you get the log?

**Comment by jsilvestre** [comment]
Sorry, I didn't acknowledge that. Yes, I got it, thanks. I'm working towards a fix, thank you very much.

**Comment by ZeHiro** [comment]
thank you :+1:

**Comment by ZeHiro** [comment]
I got this problem with other events. I can provide info if necessary.

**Comment by ZeHiro** [comment]
Fixed with version 1.0.25

**Comment by clochix** [comment]
Thanks for checking @ZeHiro ☺
